data update: 2017_04_12_12

diff --git a/shell/img b/shell/img
--- a/shell/img
+++ b/shell/img
@@ -1,6 +1,9 @@
 #!/bin/bash
 PROGNAME=$(basename $0)
 VERSION="1.0"
+IS_BACKUP=true
+IMG_EXTENSIONS=("png" "jpeg")
+IMG_QUALITY=160
 
 usage() {
     echo "Usage: $PROGNAME [OPTIONS] FILE"
@@ -9,11 +12,20 @@ usage() {
     echo "Options:"
     echo "  -h, --help"
     echo "      --version"
-    echo "  -a, --long-a ARG"
-    echo "  -b, --long-b [ARG]"
-    echo "  -c, --long-c"
+    echo "  -r, --resize width [file]"
+    echo "  -m, --merge [file]"
     echo
     exit 1
+}
+
+is_img() {
+    for ext in ${IMG_EXTENSIONS[@]}; do
+        if [ $ext == $1 ]; then
+            return 1
+            exit
+        fi
+    done
+    return 0
 }
 
 for OPT in "$@"
@@ -28,26 +40,39 @@ do
             exit 1
             ;;
         '-r'|'--resize' )
-            # img -r width file file ...
+            # img -r {width} [file file ...]
+            if [ -z "$3" ]; then
+                echo 'ERROR: not enough arg'
+                exit
+            fi
             width=$2
             shift
-            echo "Want you backup?[y/n]"
-            read backup_flag
+            # echo $IS_BACKUP
             for i in `seq 1 ${#}`
             do
                 shift
                 if [ -z "$1" ]; then
                     break
                 fi
-                if [ ${backup_flag} == "y" ]; then
+                extension=`echo $1 | cut -d"." -f2`
+                is_img $extension
+                is_img_flag=$?
+                if [ $is_img_flag == '0' ]; then
+                    continue
+                fi
+                if [ ${IS_BACKUP} == true ]; then
                     file_name=`echo $1 | cut -d"." -f1`
                     extension=`echo $1 | cut -d"." -f2`
                     imageName=$file_name\_r\.$extension
-                elif [ ${backup_flag} == "n" ]; then
+                elif [ ${IS_BACKUP} == false ]; then
                     imageName=$1
                 fi
-                echo $imageName
                 convert -filter box -resize $width $1 $imageName
+                if [ $? -gt 0 ]; then
+                    echo 'error'
+                    exit 1
+                fi
+                echo 'success >>' $imageName
             done
             exit 1
             ;;
@@ -60,9 +85,18 @@ do
                 imageNames=$imageNames' '${1}
                 imageCount=`expr $imageCount + 1`
             done
-            percentage=`expr 100 / $imageCount`
+            percentage=`expr $IMG_QUALITY / $imageCount`
             convert -geometry $percentage% +append $imageNames out_m.png
+            if [ $? -gt 0 ]; then
+                echo 'error'
+                exit 1
+            fi
+            echo "success >> out_m.png"
             exit 1
+            ;;
+        '-f'|'--forceoverwrite' )
+            IS_BACKUP=false
+            shift
             ;;
         '--'|'-' )
             shift 1
@@ -89,59 +123,7 @@ if [ -z $param ]; then
     exit 1
 fi
 
-# #!/bin/sh
-# # imgMerge a.png b.png -> out.png
-#
-# error() {
-#     echo "Plese set option.\n \
-    #         -m, --merge\n \
-    #         -p, -plus\n \
-    #         -d,  --decrease"
-# }
-#
-# main() {
-#     echo "$1"
-#     while getopts ab:c: OPT
-#     do
-#         case $OPT in
-#             "a" ) echo "a" ;;
-#             "b" ) echo "b" ;;
-#             "c" ) echo "c" ;;
-#         esac
-#     done
-#     if [ -n "$1" ]; then
-#         echo "aru"
-#         # Get file
-#         # force push
-#         case "$1" in
-#             "-m" | "--merge" ) echo "switch: m"
-#                 break ;;
-#             * ) echo "その他"
-    #                 break ;;
-    #         esac
-    #
-    #         if [ $1 = "-m" -o $1 = "--merge" ]; then
-    #             echo "-mきた"
-    #             # imageNames=()
-    #             # imageCount=0
-    #             # for i in `seq 1 ${#}`
-    #             # do
-    #             #     imageNames+=(${1})
-    #             #     imageCount=`expr $imageCount + 1`
-    #             #     shift
-    #             # done
-    #             # percentage=`expr 100 / $imageCount`
-    #             # convert -geometry $percentage% +append $imageNames out_m.png
-    #         fi
-    #         # if [ $1 = "-r" -o $1 = "--resize"]; then
-    #         # if [ $1 = "-r"]; then
-    #         # convert -filter box -resize $2 $3 out_r.png
-    #         # fi
-    #         # if [ $1 = "-h" -o $1 = "--help" ]; then
-    #         #     error()
-    #         # fi
-    #     fi
-    # }
-    #
-    # main
-    #
+# echo "Want you backup?[y/n]"
+# read backup_flag
+# if [ ${backup_flag} == "y" ]; then
+# elif [ ${backup_flag} == "n" ]; then
